In [2]:
import numpy as np

In [3]:
# numpy array 
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
# Using np.array() with a tuple
arr2 = np.array((1,2,3,4,5))
arr2

array([1, 2, 3, 4, 5])

In [5]:
# array using all zeros
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# array using all ones
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# using arange
# Similar to Python range()
# Generates evenly spaced values
# Syntax: np.arange(start, stop, step)
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
# Using np.linspace()
# Generates a fixed number of evenly spaced values
# between start and stop (inclusive)

linspace = np.linspace(0,1,5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
# Using np.eye()
# Creates an identity matrix
# Diagonal values = 1
# Other values = 0

identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# np.random.rand()
# Random numbers between 0 and 1
# Uniform distribution

random_array = np.random.rand(2,3)
random_array

array([[0.94439953, 0.60975576, 0.48071802],
       [0.00340754, 0.07168437, 0.53819466]])

In [13]:
# np.random.randn()
# Random numbers from standard normal distribution
# Mean = 0, Std Dev = 1
random_arr = np.random.randn(2,3)
random_arr

array([[-0.79726188, -1.20416639, -0.66801422],
       [-1.78487486, -1.96755479,  0.76840622]])

In [17]:
# np.random.randint()
# Random integers within a range
# Syntax: randint(low, high, size)

random_arr = np.random.randint(100,200 , size = (5,5))
random_arr

array([[109, 104, 185, 168, 136],
       [123, 122, 114, 115, 126],
       [118, 104, 111, 108, 154],
       [127, 106, 195, 144, 134],
       [144, 154, 115, 108, 140]])

In [20]:
## 3. SLICING IN ARRAYS
# Sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [21]:
# Basic slicing in 1D
# Syntax: array[start:end]
# end is excluded

In [22]:
arr[2:5]

array([30, 40, 50])

In [23]:
arr[:4]

array([10, 20, 30, 40])

In [24]:
arr[1:]

array([20, 30, 40, 50, 60, 70])

In [25]:
# reverse the arry
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [27]:
# Using step size
# Syntax: array[start:end:step]
arr[::2]

array([10, 30, 50, 70])

In [28]:
# Negative indexing
# last number
arr[-1]

np.int64(70)

In [29]:
# last 3 elements
arr[-3:]

array([50, 60, 70])

In [31]:
# # 4. SLICING IN 2D ARRAYS

matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [12,13,14,16]
])

In [ ]:
# Row slicing
# first two rows
matrix[2:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
# Column slicing
# ":" means all rows
# Second Column
matrix[: , 3]

array([ 4,  8, 12, 16])

In [38]:
# print the matrix 
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [12, 13, 14, 16]])

In [46]:
# Specific row and column range : Submatrix
# rows 1 to 2
# columns 1 to 3
matrix[1:3 , 1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [47]:
# Select a specific row
matrix[2]

array([ 9, 10, 11, 12])

In [48]:
matrix[3]

array([12, 13, 14, 16])

In [49]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [12, 13, 14, 16]])

In [50]:
matrix[2,3]

np.int64(12)

In [53]:
# Slice creates a VIEW (usually no extra memory)
# Changes affect original array
view_arr = arr[1:4]
view_arr

array([20, 30, 40])

In [56]:
view_arr[0]= 99
view_arr

array([99, 30, 40])

In [57]:
arr

array([10, 99, 30, 40, 50, 60, 70])

In [58]:
# Explicit copy creates independent data
# Changes do NOT affect original array
copy_arr = arr.copy()
copy_arr

array([10, 99, 30, 40, 50, 60, 70])

In [59]:
copy_arr[0] = 100
copy_arr

array([100,  99,  30,  40,  50,  60,  70])

In [60]:
arr

array([10, 99, 30, 40, 50, 60, 70])

In [65]:
print("all aobut today")
# np.array() -> Create array from list/tuple
# np.zeros() -> Array filled with 0s
# np.ones() -> Array filled with 1s
# np.arange() -> Evenly spaced values using step size
# np.linspace() -> Fixed number of equally spaced values
# np.eye() -> Identity matrix
 
# arr[start:end]
# arr[start:end:step]
# arr[::-1] -> Reverse array
# arr[-1] -> Last element
 
# matrix[row_slice, col_slice]
# matrix[:,1] -> Entire 2nd column
# matrix[1:3,1:4] -> Submatrix

all aobut today
