## Introduction :  Advance python

In [ ]:
# pip install numpy

In [12]:
import numpy as np

In [23]:
import numpy as np
a=[10,9,8,7]
print(np.array(a))

[10  9  8  7]


In [ ]:
# arry using tuple
arr = np.array((1,2,34,5))
arr

array([ 1,  2, 34,  5])

In [38]:
# 1d array
new_arry=np.array([1,23,3])
new_arry


array([ 1, 23,  3])

In [37]:
# 2d array
arr2 = np.array([[1,2,3],[9,8,4]])
arr2

array([[1, 2, 3],
       [9, 8, 4]])

In [ ]:
# zeros array i want to print 5 times zero
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [ ]:
one = np.ones(2)
one

array([1., 1.])

In [45]:
zeros_2 = np.zeros((2,3))
zeros_2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
ones_2 = np.ones((5,10))
ones_2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# random integers

random_integer = np.random.rand(2,4)
random_integer

array([[0.37526935, 0.68923851, 0.70004605, 0.96767425],
       [0.63165851, 0.91530894, 0.78852826, 0.90189245]])

In [22]:
import numpy as np
arr = np.empty((4, 3), dtype=np.int32)
print(arr)


[[        -1 2146435071         -1]
 [  -1048577          0 1073741824]
 [         0 1018167296          0]
 [   1048576          1          0]]


In [19]:
arr.ndim

2

In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
# basic arry attributes


#  shape  # show array
# - dtype  # show data type
# - size  # show size of array
# - ndim   #show dimension of array

# - np.array(): Creates 1D, 2D, or N-dimensional arrays
# - np.zeros()/np.ones(): Creates arrays filled with zeros or ones
# - np.arange()/np.linspace(): Generates numeric sequences
# - np.reshape(): Changes the shape of an array
# - np.sum()/np.mean()/np.max()/np.min(): Performs mathematical operations
# - np.dot(): Matrix and vector multiplication
# - Array slicing and indexing: arr[start:stop], arr[row, col]
# - Broadcasting: Automatic shape alignment during operations

In [10]:
import numpy as np
arr = np.array([ [0, 4, 2],
                 [3, 4, 5],
                 [23, 4, 5],
                 [2, 34, 5],
                 [5, 6, 7] ])
print(arr.shape)

(5, 3)


In [58]:
arr.shape

(2, 3)

In [59]:
arr.dtype

dtype('int64')

In [60]:
arr.size

6

In [63]:
arr.ndim

2

In [2]:
import numpy as np
arr = np.arange(1, 20, 2, dtype=np.float32)
print(arr)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


# Array opeations -->

In [65]:
a = np.array([1,2,3])
b = np.array([5,6,7])

In [66]:
print(a+b)

[ 6  8 10]


In [67]:
print(a-b)

[-4 -4 -4]


In [68]:
print(a*b)

[ 5 12 21]


In [69]:
print(a/b)

[0.2        0.33333333 0.42857143]


In [3]:
# slicing the elements
import numpy as np
a =  np.array([10,20,30,40,50])
a[0:3]

array([10, 20, 30])

In [73]:
a[-1]

np.int64(50)

In [76]:
a[:-1]

array([10, 20, 30, 40])

In [ ]:
#reverse
a[::-1]

array([50, 40, 30, 20, 10])

In [74]:
a.dtype

dtype('int64')

In [ ]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))

150
30.0
30.0


In [8]:
#using arange
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#using linspace() = generate evenly spaced values 

linespace = np.linspace(0,1,5)
linespace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
linespace = np.linspace(0,10,10) # i want 10 partition of 0 to 20
linespace

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [17]:
#no.random.rand()

random_array = np.random.rand(2,3)
random_array

array([[0.43429854, 0.2715982 , 0.36346245],
       [0.63468066, 0.26973671, 0.48834026]])

In [ ]:
#no.random.randn()   addend n at last
#random numbers started from normal distribution
#mean =0, std dev = 1

random_arr = np.random.randn(2,3)
random_arr


array([[ 2.43251946, -0.02309039, -0.11487571],
       [-2.67675014, -1.4461888 ,  0.54859785]])

In [19]:
random_arr = np.random.randn(4,6)
random_arr


array([[ 0.12822445,  0.25122139, -1.01970123,  1.31135204,  0.40326945,
         0.21057056],
       [-1.24280837,  0.20181069, -0.13910035, -0.3169961 ,  2.05785263,
        -0.37844799],
       [ 0.01289841, -0.06302974, -0.56603729, -0.15309319, -1.75525858,
         0.98583538],
       [ 1.42492002,  0.13107558, -1.49672426,  1.63332672, -0.15447278,
        -0.28072229]])

In [20]:
random_arr = np.random.rand(4,6)
random_arr


array([[0.97512189, 0.34856936, 0.24117583, 0.37013083, 0.75547919,
        0.2566886 ],
       [0.27225915, 0.16399327, 0.34773481, 0.78909986, 0.9744161 ,
        0.65978087],
       [0.82421421, 0.25741394, 0.88200366, 0.5093762 , 0.66834071,
        0.54719338],
       [0.96583596, 0.92301019, 0.63203443, 0.53880891, 0.67752188,
        0.37254623]])

In [ ]:
#syntax ()

random_arr = np.random.randint(1,100,size =(5,5))
random_arr

array([[86, 80,  6, 15, 82],
       [28, 77, 92, 58, 78],
       [94, 86, 23, 51,  5],
       [16, 66, 79, 34, 55],
       [30, 41, 74, 34, 24]], dtype=int32)

In [22]:
random_arr = np.random.randint(100,200,size =(10,10))
random_arr

array([[111, 147, 176, 177, 187, 194, 197, 130, 140, 198],
       [161, 146, 124, 162, 189, 169, 197, 185, 168, 131],
       [146, 155, 182, 110, 143, 149, 169, 126, 178, 118],
       [160, 119, 135, 140, 153, 134, 168, 159, 101, 185],
       [165, 150, 104, 169, 115, 194, 148, 110, 161, 184],
       [153, 157, 143, 169, 123, 154, 174, 108, 133, 116],
       [109, 133, 145, 147, 122, 105, 125, 130, 109, 192],
       [158, 124, 114, 119, 147, 101, 175, 109, 193, 148],
       [188, 135, 143, 129, 111, 197, 113, 161, 155, 161],
       [174, 102, 142, 108, 129, 173, 104, 108, 181, 140]], dtype=int32)

In [26]:
#SLICING IN ARRAYS
# simple 1d array

arr =np.array([10,20,30,40,50,60,70])
arr

arr[2:5]

array([30, 40, 50])

In [30]:
arr[:]

array([10, 20, 30, 40, 50, 60, 70])

In [28]:
arr[:4]

array([10, 20, 30, 40])

In [29]:
arr[1:]

array([20, 30, 40, 50, 60, 70])

In [31]:
# reverse array
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [32]:
# i want evry 2nd element
arr[::2]

array([10, 30, 50, 70])

In [34]:
# negative indexing - reverse
#i want last element

arr[-1]

np.int64(70)

In [ ]:
# i want last 3 elements
arr[-3::]

array([50, 60, 70])

In [51]:
## SLICING FOR 2D ARRAY

matrix = np.array([[1,2,3,4],
                    [5,6,7,8],
                   [9,10,11,12],
                   [12,13,14,15]]
                   )

In [52]:
# row slicing = 1st 2 row

matrix[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
# : means all rows
matrix[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [12, 13, 14, 15]])

In [54]:
#column slicing
#second column all roes but 2nd column

matrix[: , 1]

array([ 2,  6, 10, 13])

In [55]:
matrix[: , 3] # last column

array([ 4,  8, 12, 15])

In [56]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [12, 13, 14, 15]])

In [57]:
matrix [1:3 , 1:4]  # 1:3 is for row info n rest column info

array([[ 6,  7,  8],
       [10, 11, 12]])

In [58]:
matrix [0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [59]:
# select a spexific row
matrix[2]

array([ 9, 10, 11, 12])

In [61]:
matrix[3]

array([12, 13, 14, 15])

In [ ]:
# pick specific element ssecond row 3rd column
matrix[2,3]

np.int64(12)

In [63]:
matrix[3,2]

np.int64(14)

In [13]:
view_arr = arr[1:4]
view_arr

array([3., 5., 7.], dtype=float32)

In [14]:
# added the new element at index 0
view_arr[0]=99
view_arr


array([99.,  5.,  7.], dtype=float32)

In [15]:
copy_arr = arr.copy()
arr

array([ 1., 99.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [16]:
copy_arr[0]=100
copy_arr



array([100.,  99.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.],
      dtype=float32)

In [ ]:
#make the idetity matrix = diagonal values become 1
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])